nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:3000"]
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["POST", "GET", "OPTIONS"]
    max_age: 3600
    allow_credentials: true
  paths:
    "^/api/": # Changez cela selon vos besoins
      allow_origin: ["http://localhost:3000"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["POST", "GET", "OPTIONS"]
      max_age: 3600
      allow_credentials: true
