nelmio_api_doc:
  documentation:
    info:
      title: Viola Corp API
      description: Documentation de l'API du magasin Viola Corp
      version: 1.0.0

    components:
      securitySchemes:
        Api-Token:
          type: apiKey
          name: Api-Token
          in: header
    security:
      - Api-Token: []
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

