controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
uploads_images:
  path: /uploads/images/{filename}
  controller: App\Controller\InstrumentCardController::serveImage
